#!/bin/bash
set -e

# AI Contrarian Bot - VPS Setup Script
# For Ubuntu 24.04/26.04
# Usage: chmod +x setup-vps.sh && sudo ./setup-vps.sh

echo "=========================================="
echo "AI Contrarian Bot - VPS Setup"
echo "=========================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Please run as root (sudo ./setup-vps.sh)${NC}"
    exit 1
fi

# Detect Ubuntu version
UBUNTU_VERSION=$(lsb_release -rs)
echo -e "${GREEN}Detected Ubuntu ${UBUNTU_VERSION}${NC}"

# Update system
echo -e "${YELLOW}Updating system packages...${NC}"
apt-get update
apt-get upgrade -y

# Install essential packages
echo -e "${YELLOW}Installing essential packages...${NC}"
apt-get install -y \
    curl \
    wget \
    git \
    unzip \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release

# Install Node.js 20.x
echo -e "${YELLOW}Installing Node.js 20.x...${NC}"
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs

# Verify Node.js installation
NODE_VERSION=$(node --version)
NPM_VERSION=$(npm --version)
echo -e "${GREEN}Node.js ${NODE_VERSION} installed${NC}"
echo -e "${GREEN}npm ${NPM_VERSION} installed${NC}"

# Install Docker
echo -e "${YELLOW}Installing Docker...${NC}"
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
rm get-docker.sh

# Install Docker Compose
echo -e "${YELLOW}Installing Docker Compose...${NC}"
curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Verify Docker installation
DOCKER_VERSION=$(docker --version)
COMPOSE_VERSION=$(docker-compose --version)
echo -e "${GREEN}${DOCKER_VERSION} installed${NC}"
echo -e "${GREEN}${COMPOSE_VERSION} installed${NC}"

# Install PM2 globally
echo -e "${YELLOW}Installing PM2...${NC}"
npm install -g pm2

# Verify PM2 installation
PM2_VERSION=$(pm2 --version)
echo -e "${GREEN}PM2 ${PM2_VERSION} installed${NC}"

# Create application directory
APP_DIR="/opt/ai-contrarian-bot"
echo -e "${YELLOW}Creating application directory at ${APP_DIR}...${NC}"
mkdir -p ${APP_DIR}
mkdir -p ${APP_DIR}/data
mkdir -p ${APP_DIR}/logs

# Create bot user
echo -e "${YELLOW}Creating bot user...${NC}"
useradd -r -s /bin/false -d ${APP_DIR} botuser || true
chown -R botuser:botuser ${APP_DIR}

# Clone repository (if not already present)
if [ ! -d "${APP_DIR}/.git" ]; then
    echo -e "${YELLOW}Cloning repository...${NC}"
    read -p "Enter Git repository URL: " REPO_URL
    git clone ${REPO_URL} ${APP_DIR}
else
    echo -e "${GREEN}Repository already exists${NC}"
fi

cd ${APP_DIR}

# Install dependencies
echo -e "${YELLOW}Installing npm dependencies...${NC}"
npm install

# Build application
echo -e "${YELLOW}Building application...${NC}"
npm run build

# Create .env file if it doesn't exist
if [ ! -f "${APP_DIR}/.env" ]; then
    echo -e "${YELLOW}Creating .env file...${NC}"
    cat > ${APP_DIR}/.env << 'EOF'
# AI Contrarian Bot - Environment Configuration
# Generated by setup-vps.sh

# AI Analysis
DEEPSEEK_API_KEY=your-deepseek-api-key-here
# OR use OpenAI instead:
# OPENAI_API_KEY=your-openai-api-key-here

# Blockchain provider (for real order execution)
WSS_PROVIDER_URL=wss://polygon-mainnet.g.alchemy.com/v2/your-key-here

# Production settings
NODE_ENV=production
PORT=3000

# Telegram Alerts (required for 24/7 notifications)
TELEGRAM_BOT_TOKEN=your-telegram-bot-token-here
TELEGRAM_CHAT_ID=your-telegram-chat-id-here

# OpenClaw (for remote bot control)
OPENCLAW_API_KEY=your-openclaw-key-here

# Database (PostgreSQL)
DATABASE_URL=postgresql://user:password@localhost:5432/ai_contrarian_bot
EOF
    echo -e "${YELLOW}Please edit ${APP_DIR}/.env with your actual credentials${NC}"
fi

# Create PM2 ecosystem file
echo -e "${YELLOW}Creating PM2 ecosystem file...${NC}"
cat > ${APP_DIR}/ecosystem.config.js << 'EOF'
module.exports = {
  apps: [
    {
      name: 'ai-contrarian-bot',
      script: 'dist/index.js',
      cwd: '/opt/ai-contrarian-bot',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000
      },
      error_file: '/opt/ai-contrarian-bot/logs/err.log',
      out_file: '/opt/ai-contrarian-bot/logs/out.log',
      log_file: '/opt/ai-contrarian-bot/logs/combined.log',
      time: true
    },
    {
      name: 'ai-contrarian-dashboard',
      script: 'npm',
      args: 'run dev:dashboard',
      cwd: '/opt/ai-contrarian-bot',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production'
      },
      error_file: '/opt/ai-contrarian-bot/logs/dashboard-err.log',
      out_file: '/opt/ai-contrarian-bot/logs/dashboard-out.log',
      time: true
    }
  ]
};
EOF

# Create systemd service for PM2
echo -e "${YELLOW}Creating systemd service for PM2...${NC}"
pm2 startup systemd -u botuser --hp ${APP_DIR}
pm2 save

# Setup UFW firewall
echo -e "${YELLOW}Configuring UFW firewall...${NC}"
ufw --force enable
ufw default deny incoming
ufw default allow outgoing

# Allow SSH
ufw allow ssh

# Allow application port
ufw allow 3000/tcp

# Allow OpenClaw Gateway port
ufw allow 18789/tcp

# Allow dashboard port (if different)
ufw allow 5173/tcp

# Reload firewall
ufw reload

echo -e "${GREEN}UFW firewall configured:${NC}"
ufw status verbose

# Create OpenClaw Gateway configuration
echo -e "${YELLOW}Creating OpenClaw Gateway configuration...${NC}"
cat > ${APP_DIR}/openclaw-gateway.json << 'EOF'
{
  "name": "ai-contrarian-bot-gateway",
  "version": "1.0.0",
  "port": 18789,
  "protocol": "websockets",
  "auth": {
    "type": "token",
    "token": "your-secure-websocket-token-here"
  },
  "commands": [
    "kill_switch",
    "manual_audit",
    "status",
    "pause",
    "resume"
  ],
  "endpoints": {
    "bot": "http://localhost:3000",
    "dashboard": "http://localhost:5173"
  }
}
EOF

echo -e "${YELLOW}Please edit ${APP_DIR}/openclaw-gateway.json with your secure token${NC}"

# Create startup script
echo -e "${YELLOW}Creating startup script...${NC}"
cat > ${APP_DIR}/start.sh << 'EOF'
#!/bin/bash
cd /opt/ai-contrarian-bot

# Start bot with PM2
pm2 start ecosystem.config.js

# Start OpenClaw Gateway (if configured)
if [ -f "openclaw-gateway.json" ]; then
    echo "Starting OpenClaw Gateway on port 18789..."
    # Add your OpenClaw Gateway start command here
fi

echo "AI Contrarian Bot started successfully!"
echo "Dashboard: http://$(hostname -I | awk '{print $1}'):3000"
echo "OpenClaw Gateway: ws://$(hostname -I | awk '{print $1}'):18789"
EOF

chmod +x ${APP_DIR}/start.sh

# Create stop script
cat > ${APP_DIR}/stop.sh << 'EOF'
#!/bin/bash
cd /opt/ai-contrarian-bot
pm2 stop all
echo "AI Contrarian Bot stopped."
EOF

chmod +x ${APP_DIR}/stop.sh

# Create status script
cat > ${APP_DIR}/status.sh << 'EOF'
#!/bin/bash
echo "=== PM2 Status ==="
pm2 status
echo ""
echo "=== Docker Status ==="
docker ps
echo ""
echo "=== UFW Status ==="
sudo ufw status
echo ""
echo "=== Application Health ==="
curl -s http://localhost:3000/health || echo "Health check failed"
EOF

chmod +x ${APP_DIR}/status.sh

# Final instructions
echo ""
echo "=========================================="
echo -e "${GREEN}VPS Setup Complete!${NC}"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Edit ${APP_DIR}/.env with your actual credentials"
echo "2. Edit ${APP_DIR}/openclaw-gateway.json with your secure token"
echo "3. Run: cd ${APP_DIR} && ./start.sh"
echo ""
echo "Useful commands:"
echo "  ./start.sh   - Start the bot"
echo "  ./stop.sh    - Stop the bot"
echo "  ./status.sh  - Check status"
echo "  pm2 logs     - View logs"
echo "  pm2 monit    - Monitor resources"
echo ""
echo "Dashboard: http://$(hostname -I | awk '{print $1}'):3000"
echo "OpenClaw Gateway: ws://$(hostname -I | awk '{print $1}'):18789"
echo ""
echo -e "${YELLOW}Remember to:${NC}"
echo "  - Set up your Telegram bot and get credentials"
echo "  - Get your DeepSeek/OpenAI API key"
echo "  - Configure your Polymarket wallet"
echo "  - Test the health endpoint: curl http://localhost:3000/health"
echo ""
